name: Run Parser

on:
  schedule:
    - cron: '30 5 * * 1' # Every Monday in 5^30 am
  workflow_dispatch:

jobs:
  run-parser:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run parser
        run: python schedule_parser.py

      - name: Check CSV output
        run: cat planer.csv

      - name: Upload CSV to Google Sheets via Apps Script
        run: |
          RESPONSE=$(curl -s -X POST -H "Content-Type: text/csv" --data-binary @planer.csv "https://script.google.com/macros/s/AKfycbxCxj32rIrMVx2EDVTDVsndlkstJbXIrGuT5VUntcKCFl45Hi1vjRjjdGGYIWyG4hgGZQ/exec")
          echo "Google Apps Script response: $RESPONSE"

