name: Run Parser

on:
  schedule:
    - cron: '0 6 * * 0'  # Каждое воскресенье в 6 утра UTC
  workflow_dispatch:

jobs:
  run-parser:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run parser
        run: python schedule_parser.py

      - name: Check CSV output
        run: cat planer.csv

      - name: Send CSV to Google Apps Script
        run: |
          RESPONSE=$(curl -s -X POST -H "Content-Type: text/csv" --data-binary @planer.csv "https://script.google.com/macros/s/AKfycbxnH6yeT8pLNbdJ7Ob273zEZZo-Z4yalOUnCnbrPZc_2Kj0Sg9_IqdqY3EjuR9bfIHvWA/exec")
          echo "Google Apps Script response: $RESPONSE"
